name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write # Add this permission

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug API Key
        env:
          MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          echo "API Key length: ${#MAPS_API_KEY}"
          echo "First 4 chars: ${MAPS_API_KEY:0:4}..."
      
      - name: Replace API Key
        env:
          MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          # Create a temporary file with the key
          echo "$MAPS_API_KEY" > key.txt
          # Use the file content to replace the placeholder
          sed -i "s|GOOGLE_MAPS_API_KEY_PLACEHOLDER|$(cat key.txt)|g" index.html
          rm key.txt
          # Verify replacement
          echo "Checking key in index.html:"
          grep -o "key=[^&]*" index.html | cut -c1-8
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build
        run: |
          # Add any build commands if needed
          echo "No build step required"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 