name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Replace API Key
        run: |
          # Create a temporary file with proper escaping
          echo "${{ secrets.GOOGLE_MAPS_API_KEY }}" > api_key.txt
          # Use the file content to replace the placeholder
          KEY=$(cat api_key.txt)
          sed -i "s|%GOOGLE_MAPS_API_KEY%|$KEY|g" index.html
          rm api_key.txt
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true # Automatically remove deleted files from the deployment 