name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Replace API Key
        env:
          MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          # Escape special characters in the API key
          ESCAPED_KEY=$(echo "$MAPS_API_KEY" | sed 's/[\/&]/\\&/g')
          # Replace the placeholder with the escaped API key
          sed -i "s/GOOGLE_MAPS_API_KEY_PLACEHOLDER/$ESCAPED_KEY/g" index.html
          # Verify the replacement (only show first few chars)
          echo "Verifying API key replacement..."
          grep -o "key=[^&]*" index.html | sed 's/\(.\{8\}\).*/\1.../'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 